name: clang-format-check
on:
  # push:
  #   branches: [Feature/cicd-gha]
  #   # Remove the line above to run when pushing to master
  pull_request:
    branches: [main]

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'src'
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.10.2
      with:
        clang-format-version: '15'
        check-path: ${{ matrix.path }}
        fallback-style: 'Google' # optional